### ISSUE TITLE
"window is not defined" error when importing flowbite

### ISSUE THREAD

**Issue by Collo-V** [themesberg/flowbite#226]
Hello guys. I'm excited to use flowbite with my nuxt project but when I import it in my nuxt.config.js file, I get the warning 'window is not defined'. Any help...? Thanks
![flow'Bite error](https://user-images.githubusercontent.com/60650741/181775179-ac841319-4f45-452b-a3cd-d780bddedb45.png)
'

**Comment by zoltanszogyenyi** [comment]
Hey @Collo-V,

Please check out the [Flowbite Vue repository](https://github.com/themesberg/flowbite-vue) and the [Flowbite Vue website](http://flowbite-vue.com/) for Nuxt and Vue 3.

**Comment by Collo-V** [comment]
Thanks @zoltanszogyenyi

**Comment by 23tux** [comment]
I don't use Vue or Nuxt.js so far, but I guess I have the same error, although in a slightly different combination:

Rails app with the vite_ruby gem and WindiCSS instead of Tailwind. This is my `windi.config.ts`:

```
import { defineConfig } from "windicss/helpers";
import flowbite from "flowbite";

export default defineConfig({
  theme: {
    extend: {},
  },
  plugins: [flowbite.plugin],
  content: [
    "./node_modules/flowbite/**/*.js",
  ],
});
```

When I start the dev server with `bin/vite dev` everything works in the browser (styles, dropdowns...). But as soon as I run `bin/vite build` I get the same error as OP:

```
root@06c15a9dcd39:/usr/src/app# bin/vite build --clear
Removed vite cache and output dirs:
        /usr/src/app/public/vite
        /usr/src/app/public/vite-ssr
        /usr/src/app/tmp/cache/vite
        /usr/src/app/node_modules/.vite
Building with Vite ⚡️
error during build:
ReferenceError: window is not defined
    at /usr/src/app/node_modules/flowbite/dist/flowbite.js:165:3
    at /usr/src/app/node_modules/flowbite/dist/flowbite.js:3992:13
    at jiti (/usr/src/app/node_modules/jiti/dist/jiti.js:1:247502)
    at /usr/src/app/windi.config.ts:2:40
    at jiti (/usr/src/app/node_modules/jiti/dist/jiti.js:1:247502)
    at loadConfiguration (/usr/src/app/node_modules/@windicss/config/dist/index.js:86:20)
    at resolveOptions (/usr/src/app/node_modules/@windicss/plugin-utils/dist/index.js:428:99)
    at _init (/usr/src/app/node_modules/@windicss/plugin-utils/dist/index.js:934:21)
    at Object.ensureInit (/usr/src/app/node_modules/@windicss/plugin-utils/dist/index.js:951:23)
    at configResolved (/usr/src/app/node_modules/vite-plugin-windicss/dist/index.js:319:19)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63270:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63270:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doBuild (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45673:20)
    at async build (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45662:16)
    at async CAC.<anonymous> (file:///usr/src/app/node_modules/vite/dist/node/cli.js:748:9)
```

Any idea how to solve this @Collo-V or @zoltanszogyenyi?
