### ISSUE TITLE
Flowbite is not properly working for > 1.5.0 under Rails 7 with importmaps

### ISSUE THREAD

**Issue by mwalkowiak** [themesberg/flowbite#342]
I had my Rails 7 setup with tailwind and flowbite. I introduced some flowbite components like menu, dropdown etc and it stops working for a version greater than 1.5.0.

I am seeing these errors below, but I am not sure if they are related:

```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Collapse._init (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:7459)
    at new Collapse (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:7175)
    at flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:8376
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:8285)
    at domContentLoadedCheck (es-module-shims.js:797:16)
    at HTMLDocument.<anonymous> (es-module-shims.js:803:7)
flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Collapse._init (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:7459)
    at new Collapse (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:7175)
    at flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:8376
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (flowbite-a65aca0f047a72010d550ef7c1c1eb242f8fc5e38f875a995678a99c486aa88b.js:1:8285)
```

**Comment by zoltanszogyenyi** [comment]
Hello @mwalkowiak,

I'll have a look at this for the v1.6.0 update. I will close this issue though because there's already one opened here: https://github.com/themesberg/flowbite/issues/88
