### ISSUE TITLE
flowbite.com having next.js uncaught client-side exception  

### ISSUE THREAD

**Issue by dizys** [themesberg/flowbite#694]
**Describe the bug**
Flowbite.com is currently down with uncaught client-side exception.

**To Reproduce**
1. Go to Flowbite.com
2. Observe.

**Expected behavior**
Flowbite.com should open up fine.

**Screenshots**
![image](https://github.com/themesberg/flowbite/assets/23469706/1afb99d7-dbe6-4cc3-82cf-55c16803e01e)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chromium
 - Version: 118

**Additional context**
Console logs:
```
Failed to load resource: the server responded with a status of 403 ()
api.github.com/repos/themesberg/flowbite:1 
       Failed to load resource: the server responded with a status of 403 ()
script.js:1 
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
framework-d51ece3d757c7ed2.js:1 TypeError: s.map is not a function
    at u (index-cba5d13bc433a2db.js:1:78568)
    at Eo (framework-d51ece3d757c7ed2.js:1:63193)
    at Pu (framework-d51ece3d757c7ed2.js:1:74881)
    at xi (framework-d51ece3d757c7ed2.js:1:121316)
    at bs (framework-d51ece3d757c7ed2.js:1:109369)
    at gs (framework-d51ece3d757c7ed2.js:1:109297)
    at vs (framework-d51ece3d757c7ed2.js:1:109160)
    at as (framework-d51ece3d757c7ed2.js:1:105940)
    at ls (framework-d51ece3d757c7ed2.js:1:104491)
    at S (framework-d51ece3d757c7ed2.js:1:138451)
du @ framework-d51ece3d757c7ed2.js:1
main-e3ee4f9da2049d71.js:1 TypeError: s.map is not a function
    at u (index-cba5d13bc433a2db.js:1:78568)
    at Eo (framework-d51ece3d757c7ed2.js:1:63193)
    at Pu (framework-d51ece3d757c7ed2.js:1:74881)
    at xi (framework-d51ece3d757c7ed2.js:1:121316)
    at bs (framework-d51ece3d757c7ed2.js:1:109369)
    at gs (framework-d51ece3d757c7ed2.js:1:109297)
    at vs (framework-d51ece3d757c7ed2.js:1:109160)
    at as (framework-d51ece3d757c7ed2.js:1:105940)
    at ls (framework-d51ece3d757c7ed2.js:1:104491)
    at S (framework-d51ece3d757c7ed2.js:1:138451)
```

**Comment by dizys** [comment]
Just refreshed. Seems resolved.
