### ISSUE TITLE
Cannot build project using flowbite 2.5.0

### ISSUE THREAD

**Issue by NTICompass** [themesberg/flowbite#942]
I am using flowbite in my project.  With v2.4.1, vite was able to build without issue.

Today, I updated to v2.5.0 and suddenly vite won't build it.  Here's what it's saying:

```
[vite:css] [postcss] Cannot find module 'typescript'
Require stack:
- /home/nticompass/Code/my_project/node_modules/flowbite/plugin.js
file: /home/nticompass/Code/my_project/resources/css/index.css:undefined:NaN
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at _resolve (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:241814)
    at jiti (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:244531)
    at /home/nticompass/Code/my_project/node_modules/flowbite/plugin.js:6:23
    at evalModule (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:245241)
    at /home/nticompass/Code/my_project/tailwind.config.mjs:1:246
    at evalModule (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/home/nticompass/Code/my_project/node_modules/jiti/dist/jiti.js:1:245241)

Process finished with exit code 1
```

From what I can find, the issue seems to be the following line in `plugin.js`: https://github.com/themesberg/flowbite/blob/878ced1b622d1c48fece24bfbc4cd0064941bea6/plugin.js#L6

This import doesn't seem to be used anywhere in the file, and removing it seems to fix the issue.

**Comment by zoltanszogyenyi** [comment]
Fixed with https://github.com/themesberg/flowbite/releases/tag/v2.5.1
